### ISSUE TITLE
scripting regression

### ISSUE THREAD

**Issue by judell** [xmlui-org/xmlui#994]
@Dotneteer in 0.9.2, functions defined in foo.xmlui.xs don't seem to be available to foo.xmlui.

If I roll back to 0.8.5 it works.

Related to recent script-related commits maybe?

**Comment by Dotneteer** [comment]
Thanks for reporting it. We changed to a new scripting engine in 0.9.0; as I see, it still has bugs.

**Comment by Dotneteer** [comment]
@judell, where can I find the foo.xmlui.xs file you mentioned above?

**Comment by judell** [comment]
it was just 

function foo() {
  return 'foo'
}

in other words, define any function in a .xs, then try to call it.

<img width="856" alt="Image" src="https://github.com/user-attachments/assets/d349b18a-b964-4231-8b2f-e5f289f79b9d" />

**Comment by Dotneteer** [comment]
I fixed several scripting related bug in #983. Those fixes solved this issue; your sample code works on my machine with the latest xmlui build (0.9.5).

**Comment by judell** [comment]
@Dotneteer at http://hn.jonudell.info/xmlui-cms/#/palettes using 0.9.8 I'm still seeing the above: the function defined in Palettes.xmlui.xs is undefined when called from Palettes.xmlui. If I drop back to 0.8.5 it works.

**Comment by Dotneteer** [comment]
@judell, Thanks for the sample! I reproduced the issue and fixed it. This issue manifested only for non-built apps due to an issue in our `StandaloneApp` React component.

Now, it's working in xmlui v0.9.9. You will find the demonstration in my xmlui-cms branch here: https://github.com/JonUdell/xmlui-cms/tree/dotneteer/fix-code-behind
